### ISSUE TITLE
12.09. Web Audio Event

### ISSUE THREAD

**Issue by janl** [rmehner/jsfest.berlin#11]

**Comment by theophani** [comment]
@janmonschke: Now that I have seen the new SoundCloud space, I have a some idea of where we can host this in the SoundCloud office. Are you in Berlin next week to come and have a look, and hopefully we can confirm the space right then?

**Comment by janmonschke** [comment]
Yes, I am in Berlin next week and I would love to check out the new office.
I'm available on Wednesday and Thursday, which one works best for you?

I'm currently writing the mail to Google and Mozilla and will send you a
draft layer today.

**Comment by theophani** [comment]
Thursday is wide open for me. Anytime but 16:00 works.

**Comment by janmonschke** [comment]
Perfect :)
Let's meet earlyish then. Around 10am or 11am if that works for you.
Should we meet at the factory? (If yes, can you post the address?)

**Comment by theophani** [comment]
Let's go with 10:30 ;)

Here is how to get into the building:

![hq map](https://cloud.githubusercontent.com/assets/364246/3269921/a1fccf76-f2f7-11e3-93ca-16e75b6aea09.jpg)

Some up to the office (2nd floor) and I’ll meet you there.

**Comment by janmonschke** [comment]
:+1:

**Comment by janmonschke** [comment]
I checked out the location at Soundcloud today together with @theophani. She has found the perfect location for ~40 people and this event is definitely going to happen. Further I asked if Mozilla and Google want to help sponsoring the event.

**Comment by rmehner** [comment]
I talked to Paul Irish at JSConf, he was definitely down with telling some people of the Chrome team about it. Gonna mail him later today and point him towards here. Would love to have some browser vendors on board :)

**Comment by janmonschke** [comment]
That would be amazing :)

**Comment by chrisguttandin** [comment]
Hello everybody, I contacted Jan last week and offered my help because I very much like the idea of a Web Audio Event. He asked me to introduce myself here and that's what I am doing now. :-)

**Comment by janmonschke** [comment]
Hey everyone!

a lot of things happened recently and the event is really taking shape!

1) We now have an event on EventBrite for people to sign up: https://www.eventbrite.co.uk/e/web-audio-hack-day-tickets-12451959145 (If you're helping you don't need a ticket). This event will be communicated via Twitter next week.

2) We are happy to have @sole from Mozilla on board! She will give an introduction to the Web Audio API to everyone :)

3) We need a website that either contains a tutorial for people to learn the Web Audio API step by step or a website that shows helpful links with material on the API. Sadly I don't have time to work on this myself. Is there anyone who can help creating that? (@chrisguttandin @woodworker et al?)

Some resources:
- JavaScript is the new Punk Rock https://www.youtube.com/watch?v=PN8Eg1K9xjE 
- Stuart Memo intro to Web Audio API http://stuartmemo.com/an-introduction-to-the-web-audio-api/
- Intro tutorial to Web Audio API http://www.html5rocks.com/en/tutorials/webaudio/intro/
- Intro to Web Audio (including sequencer) http://janmonschke.com/Music-with-JS-and-Gamepads/#/ 
- Book on Web Audio http://chimera.labs.oreilly.com/books/1234000001552 
- Cool tool to show how the routing works http://uglyhack.appspot.com/webaudiotoy/

4) We're partnering up with the Web Music Hack Day in Japan. They are organizing an event on the 13th of September and have given us valuable feedback on how to organize it. Also they sent us a link to their learning material (in Japanese):
- https://github.com/ryoyakawai/WebMusicDevelopersJP/tree/master/codeLabs
- http://www.g200kg.com/jp/docs/webaudio/
- https://rawgit.com/ryoyakawai/WebMusicDevelopersJP/master/codeLabs/WebMIDIAPI/index.html

We will share blog posts with them about both events and capture videos of the presentations!

Maybe we can use this material for our event as well.

**Comment by woodworker** [comment]
another nice tool for playing around with webaudio is http://wavepot.com/
ill be back in the internet at monday, need to listen to a lot of loud music on the weekend

i know someone from bitwig, i ask if they want to sponsor a bit,
they also like javascript, as all of their scripts for controller support for the DAW are written in javascript

**Comment by chrisguttandin** [comment]
Thanks for the update. I am very busy at the moment but I guess everyone is busy somehow. I think I can fit in some hours at the end of this week to work on the website. I can do the technical part but I would really appreciate if someone else did a simple design for it. Do you know someone who could do that?

Maybe we could have a quick chat about it tomorrow.

**Comment by janmonschke** [comment]
Hey everyone :)

The event has sold out yesterday and the waiting list is filling up :)

In addition to our first speaker, Soledad Penadés, we now also have Chris Wilson from Google on board for the event \o/

Hope you enjoyed Wacken @woodworker ;)

Who in here feels like being able to attend the event as a facilitator (helping attendees with the API)? (/cc @chrisguttandin @mrflix)

**Comment by woodworker** [comment]
i wasn't at wacken, was at Schlagstrom

at the moment i'm looking into WebMidi[1] and NoFlo-Webaudio [2]
to get some easy sample code done for people to start with
and to get into the web audio api stuff at all

does already a design appeared from somewhere for the event page?
or do we need to come up with one our selfs?

do we want to add some basic samples on the event page to play around
or just a link page with all the tutorials an resources?

[1] Web Midi
https://plus.google.com/+ChrisWilson/posts/cs4J6sS9qmJ
chrome://flags/#enable-web-midi
http://webaudio.github.io/web-midi-api/
https://github.com/cwilso/WebMIDIAPIShim

[2] NoFlo Web Audio
http://meemoo.org/blog/2014-08-05-first-steps-for-noflo-webaudio/
https://github.com/automata/noflo-webaudio
http://app.flowhub.io/#example/04847249319d2326fa92
https://www.kickstarter.com/projects/noflo/noflo-development-environment/posts/943774

**Comment by woodworker** [comment]
i can bring some usb midi devices for testing webmidi
- bcr2000 (which also has midi in/out/through)
- mpkmini
- korg nanopad

**Comment by janmonschke** [comment]
Sorry for being so quiet in the last weeks, many things have happened in the meantime :)

Great idea to bring MIDI devices. I will bring my mini DJ device as well!

Actually, we will have prizes for the three best audio demos in the form of MIDI devices.

I thought about these:
- http://www.amazon.de/KORG-nanoPAD2-USB-MIDI-Controller-Triggerpads-Schwarz/dp/B004M8YPKM
- http://www.amazon.de/Akai-LPK25-Performance-Keyboard-Minitasten/dp/B002M8GBDI

Any other recommendations?

PS: The prizes are not yet officially announced ;)

**Comment by woodworker** [comment]
Does Webaudio has a Logo?
If not how about this?

http://prolope.de/svg/webaudio-js.svg
JS Logo + Public Domain Speaker Icon

Source: http://commons.wikimedia.org/wiki/File:Speaker_Icon.svg

**Comment by woodworker** [comment]
As Prize, maybe this?
http://www.amazon.de/Akai-LPD8-MIDI-Laptop-Controller/dp/B002M8EEW8/

Like the mixture of Potis and Pads

**Comment by theophani** [comment]
That logo is rad :D

**Comment by sole** [comment]
Wow! yeah! I love it!

I think there is no official Web audio logo, I'm going to ask.

**Comment by sole** [comment]
Also @janmonschke I have the keyboard version of the Korg nanopad, they're plastic-y but for the price they are pretty decent. And they instaworked with the Web MIDI API in Chrome last time I tried!
That said I'm spoiled because I'm using Mac and MIDI is pretty decent in there, but hey, probably 99% of people are going to be using Mac too.

**Comment by janmonschke** [comment]
Absolutely love the logo @woodworker :heart: 

Thx for the input on MIDI devices. The plan was to buy three devices in total so I'll go for buying one of each so that participants can choose ;) 

@sole Would it be okay if you bring the Nanopad to the hackathon?

**Comment by sole** [comment]
@janmonschke I think it's feasible! I'll make a note for when I pack my luggage next week!

**Comment by janmonschke** [comment]
Devices are ordered, a reminder email has been sent to the attendees, Google is sponsoring snacks for dinner. I think we are ready for the event :))

**Comment by woodworker** [comment]
We now also have a Bitwig Studio License as price for tomorrow.

**Comment by jalbertbowden** [comment]
html5 api icons via w3c http://www.w3.org/html/logo/img/icons-2.png
web media api icon styled http://www.w3.org/html/logo/img/class-header-multimedia.jpg  
just for reference;  
i like yours
