### ISSUE TITLE
12.09. One Web For All Hackathon

### ISSUE THREAD

**Issue by janl** [rmehner/jsfest.berlin#12]

**Comment by Kriesse** [comment]
I’m resigning from this, got too many events already :)
Open for anyone to take on. 

Prototype:
http://onewebforall.us/

I’d be happy to make an intro to the organizers of OWFA in San Francisco, and share what I know about it, but won’t be able to do more.

**Comment by Onna-no-hito** [comment]
just a personal opinion-- i vote no hackathon! :)

**Comment by Kriesse** [comment]
Agreed. No one seems to have bandwidth for this – closing until someone else vetoes :)
(cc @theophani @ffffux)
