### ISSUE TITLE
11.09. JS Code Retreat

### ISSUE THREAD

**Issue by janl** [rmehner/jsfest.berlin#13]

**Comment by theophani** [comment]
@nonken Is this likely enough that we can add it to the schedule, even as "tentative"? We're going to launch the site soon, and I'd love to have this on the list.

**Comment by nonken** [comment]
@theophani totally, we're on board! I need to catch up on a whole bunch of emails, do you need any info at this point in time?

**Comment by theophani** [comment]
I'd love to add it to our published schedule with "more details soon" if you are sure about the date.

**Comment by nonken** [comment]
@theophani can you add @wolframkriesing to this repo? I just spoke with him and he mentioned the 12.09 so it is best to coordinate the date with him directly.

**Comment by janl** [comment]
The repo is now public

**Comment by nonken** [comment]
Oh woot

**Comment by rmehner** [comment]
Hey there, JS Code Retreat is looking for a venue that holds ~50 people for a whole day. If you have any pointers, please let us know! /cc @wolframkriesing

**Comment by baruchlab** [comment]
heya it may be possible at our space http://info.thoughtworks.com/berlin best if one of you comes by and takes a look! let me know @wolframkriesing @janl

**Comment by wolframkriesing** [comment]
@baruchlab would be awesome. can we have a quick hangout/skype call regarding details? ping me on twitter or email wolfram at uxebu. thanks
