### ISSUE TITLE
Any: Geeks go to museums

### ISSUE THREAD

**Issue by janl** [rmehner/jsfest.berlin#18]
Computer game museum
Technical museum
food etc.

**Comment by maxfell** [comment]
+1

**Comment by Kriesse** [comment]
Aw :) 
Hamburger Bahnhof (Zeitgenössisches)
Neue Nationalgalerie und drumherum (Architektur + Skulptur) 
Can make contacts to tour guides and give some orga tips.

**Comment by theophani** [comment]
@mroderick Ping! I think this is defs a go. We were leaning towards Wednesday?
