### ISSUE TITLE
Make website pretty

### ISSUE THREAD

**Issue by janl** [rmehner/jsfest.berlin#19]

**Comment by Kriesse** [comment]
Assigning it to me. 
Any deadlines / planned announcements I should be aware of? 

cc @janl @theophani

**Comment by janl** [comment]
not that I know, we can launch this unstyled any time and make pretty later :)

**Comment by Kriesse** [comment]
:+1:

**Comment by frontdevde** [comment]
Maybe help from the community might be an option here? Then we could focus on planing the actual events. I know two young guys from Hamburg (recently joined the team behind the #dec0de meetup) who most likely would love to take on this task. Shall I shoot them a mail and ask whether they would have time for this?

**Comment by janl** [comment]
On 21 May 2014, at 00:58 , Michael P. Pfeiffer notifications@github.com wrote:

> Maybe help from the community might be an option here? Then we could focus on planing the actual events. I know two young guys from Hamburg (recently joined the team behind the #dec0de meetup) who most likely would love to take on this task. Shall I shoot them a mail and ask whether they would have time for this?

+1, this is partly the reason why I suggested open sourcing the repo :)

**Comment by Kriesse** [comment]
+1 community help
But would be nice to ask Berlin locals first.

**Comment by frontdevde** [comment]
Relying on locals for the help with the events, yes. 

Not sure though why the location of contributors should be of any concern for a website? More relevant that someone has time to take on the task and focus on it, no?

**Comment by mroderick** [comment]
I have an idea for a schedule for the entire week.

Something oriented like this:

![jsfest schedule](https://cloud.githubusercontent.com/assets/20321/3080011/f494447e-e4a8-11e3-82b9-5d3d96631730.png)

**Comment by theophani** [comment]
Love it!

**Comment by janl** [comment]
+1

**Comment by Kriesse** [comment]
Was bored on a plane and pushed some initial styles:
![image](https://cloud.githubusercontent.com/assets/53684/3084288/01619e3c-e4f3-11e3-9c72-a30a4de2ebf9.png)

I added RSVP/ticket buttons as the main call to action per each event, plus optional description texts and other relevant links (e.g. Call for Speakers). Let me know if that makes sense, and what else should go on this page. 

@mroderick Love the schedule idea, this would really help to get an overview! Maybe we can come up with a color code = every major event is identified by its color that shows up as a block in the overview schedule, and can be found again in the more detailed description list (which could look like what is on the page now).

**Comment by theophani** [comment]
Looking lively! Like the colour-code idea. Maybe coded by JS / CSS / Both / Other, or some other pattern that may emerge.

**Comment by janl** [comment]
SO GOOD!

**Comment by theophani** [comment]
Who has the photo of the whiteboard with the schedule plans? Can they share it here, so we can transcribe it? Thanks!

**Comment by mroderick** [comment]
![2014-05-14 19 43 49](https://cloud.githubusercontent.com/assets/20321/3089098/a873722c-e57a-11e3-9262-84b10682b7bc.jpg)

It's the only photo I have

**Comment by janl** [comment]
My way of transcription was creating issues for all the individual events: https://github.com/rmehner/jsfest.berlin/issues?state=open

**Comment by theophani** [comment]
Ah, cool

**Comment by Kriesse** [comment]
(Obvious) inspiration for a complex event schedule: https://www.google.com/events/io/schedule

**Comment by verpixelt** [comment]
I guess we could close this issue now ;) Or would you like to keep it open until the detail pages are finished?

**Comment by Kriesse** [comment]
Yeah, close it :)
