### ISSUE TITLE
xx.09. HTMLconf EU

### ISSUE THREAD

**Issue by frontdevde** [rmehner/jsfest.berlin#23]
Last year I registered www.htmlconf.eu after a french guy dropped it in one of his tweets:

https://twitter.com/jibhaine/status/357924210733101056
https://twitter.com/jibhaine/status/357925109446623233
https://twitter.com/jibhaine/status/357942953441898496

So far there was no use case for the domain, maybe we find a use for it in the jsfest context.
Maybe create a small site that promotes jsfest, or use it for a less serious event like dhtmlconf, or ...

**Comment by Kriesse** [comment]
Closing, since noone took it on – for now, maybe just point the domain to the jsfest site?
