### ISSUE TITLE
Twitter acc for jsfest

### ISSUE THREAD

**Issue by frontdevde** [rmehner/jsfest.berlin#24]
I'm not sure whether there is already an account that I'm just not aware of but...

...it might come in handy to have a dedicated Twitter acc for jsfest. Especially during the event week itself it would be nice if people could follow one account and get all the information for all the events in one place. Might also reduce the noise in the streams of each event for people who only attend one specific event. 

I registered @jsfestberlin just in case we want to do this.

Opinions?

**Comment by maxfell** [comment]
Good idea! Even if that account mainly retweets the other accounts or vice versa it's nice to have.

**Comment by janl** [comment]
+1

**Comment by verpixelt** [comment]
+1
