### ISSUE TITLE
School of Ma/Week-long workshop after JSFest?

### ISSUE THREAD

**Issue by Onna-no-hito** [rmehner/jsfest.berlin#25]
copied from the google doc over here.
this is my idea/proposal-- basically what i want to know is-- what is the procedure for getting approval for a proposal? i'd like to know next steps if there are any. thanks!

in collaboration w/school of machines, making & make-believe (http://schoolofma.org/)-- a week-long workshop from Sept. 15-19 for 10-15 students-- selection of attendees from the weeks previous conferences (who apply)-- instructors may or may not be speakers at the conference who stay a few days extra. week of hands-on instruction/workshops around idea of "the creative web"-- think projects similar to Aaron Koblin's work: http://www.aaronkoblin.com/work.html for desginers and devs, there will be a non-outrageous fee which pays for instructors, space, admin, etc. (€350/wk reasonable?-- would like to find out conference ticket prices to take it into account) 

idea is to harness the excitement that we have after a conference--when we're at our peak of
inspiration with a strong desire to create and collaborate-- what can we accomplish if given
creative freedom, instruction and support?

**Comment by Kriesse** [comment]
@Onna-no-hito Should we close this, since no one has the bandwidth to take it on?
(Should plan another Organizers meetup though ;) )

**Comment by schoolofma** [comment]
yeah sure-- i lost the bandwidth myself-- many many things going on in this conference already:)
consider it closed!
