### ISSUE TITLE
CSSlabs / CSSclasses

### ISSUE THREAD

**Issue by Kriesse** [rmehner/jsfest.berlin#26]
cc @plique @QateOh @kriesse
- [x] Finalize concept
- [ ] Agree on schedule
- [ ] Find location(s)
- [ ] Find sponsors
- [ ] Find coaches

**Comment by Kriesse** [comment]
@plique Next step should be an organizer’s meetup ASAP, open to all people who are interested in coaching etc. Let’s agree on an evening we can both make and then invite people?

**Comment by schoolofma** [comment]
can't you just invite them to the informal eve we already have planned?
its an organisers meetup for everyone involved in jsfest, seems it would be a totally
appropriate place or?

**Comment by Kriesse** [comment]
No, this is a separate meetup – purpose should be to get CSSclasses going and work very focused on getting things done :)

**Comment by plique** [comment]
@kriesse What if we would meet also on friday at Würgeengel but earlier? (If you have the time) 18.30h or 19h? Otherwise Thursday would be our only chance, right? Or next week monday night? 

Jana Ahrens
Delbrückstraße 18
12051 Berlin

www.plique.net
jana_ahrens@plique.net

+49 (0)178 5568983

Am 23.06.2014 um 14:50 schrieb Kristina Schneider notifications@github.com:

**Comment by Kriesse** [comment]
@plique Let’s try next week then

**Comment by plique** [comment]
@kriesse what about monday night? at your kitchentable? 

Jana Ahrens
Delbrückstraße 18
12051 Berlin

www.plique.net
jana_ahrens@plique.net

+49 (0)178 5568983

Am 23.06.2014 um 15:41 schrieb Kristina Schneider notifications@github.com:

**Comment by Kriesse** [comment]
Let’s say GriGri, unless the weather isn’t nice :) More room for more people.

**Comment by plique** [comment]
@kriesse √

Am 23.06.2014 um 15:45 schrieb Kristina Schneider notifications@github.com:

**Comment by Kriesse** [comment]
This is confirmed :) Closing, further planning is happening in goodle docs / emails / face-to-face. Contact @plique or @kriesse to get involved.
