### ISSUE TITLE
Welcome guide?

### ISSUE THREAD

**Issue by mroderick** [rmehner/jsfest.berlin#27]
Do you think it would be worthwhile to publish an updated version of http://roderick.dk/geeks-welcome-to-berlin/ on the jsfest.berlin website?

**Comment by janl** [comment]
Yup! :)

**Comment by janmonschke** [comment]
Great idea!

**Comment by mroderick** [comment]
OK. I've updated the welcome guide (contributions welcome via https://github.com/mroderick/blog.jekyll/blob/master/geeks-welcome-to-berlin/index.md).

@theophani suggested that we link to it, but where would be a good place for the link?

**Comment by theophani** [comment]
I like what they did on the original JSFest SF event where at the bottom they had a Info section for this kind extra stuff:

![screen shot 2014-06-17 at 12 29 19](https://cloud.githubusercontent.com/assets/364246/3298997/648ad424-f60a-11e3-8a40-089d0269db2d.png)

**Comment by Kriesse** [comment]
+1 
I think a compact version at the bottom, with a link to the full site, would be great.

**Comment by verpixelt** [comment]
Do we want to have this integrated on the jsfest.berlin page itself? I could work something out.

**Comment by theophani** [comment]
@verpixelt If you could integrate it on the site, that would be really nice. Maybe some top line things and then a link to @mroderick’s full post?

**Comment by mroderick** [comment]
It'll probably get more attention and help more people, if it's properly integrated on the site. That would be really nice indeed

**Comment by Dangoo** [comment]
Yeah it'll be helpfull, but I'm a bit concerned about the place where to
integrate it. I'd suppose a separate page cause otherwise the events on the
main page will get more and more out of focus/viewport.

Am Donnerstag, 7. August 2014 schrieb Morgan Roderick :

> It'll probably get more attention and help more people, if it's properly
> integrated on the site. That would be really nice indeed
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rmehner/jsfest.berlin/issues/27#issuecomment-51441553
> .

## 

## 

Daniel Gooß, Development

daniel.gooss@sinnerschrader.com

SinnerSchrader Deutschland GmbH | SinnerSchrader Group
Völckersstraße 38, 22765 Hamburg, Germany

Amtsgericht Hamburg HRB-Nr. 63663
Geschäftsführer: Matthias Schrader (Sprecher), Holger Blank,
Thomas Dyckhoff, Dr. Lars Finke, Martin Gassner, Nils Wollny

Büros: Hamburg, Frankfurt a. M., München, Prag

http://www.sinnerschrader.com | Radical Relationships

**Comment by mroderick** [comment]
Yeah, let's not take too much focus away from the schedule. A separate page would also mean an easily linkable url.

**Comment by verpixelt** [comment]
Because we're talking about a welcome guide it would miss the point to place it somewhere at the bottom of the page. Maybe we can do something simple, like this:

![screen shot 2014-08-07 at 10 32 04](https://cloud.githubusercontent.com/assets/1640079/3839167/6b2c8f54-1e0d-11e4-948f-a772cd893310.png)

Therefor we should finish the layout for the detail pages to get a more consistent look.

**Comment by verpixelt** [comment]
@mroderick I have two questions. A) Could we please change the headline to "Geekettes & Geeks, welcome to Berlin" and b) I would like to add another Foursquare link and a bit additional info from a good friend of mine(she has also written a little welcome guide for CSSConf last year and would be fine with us using it). So if it is okay for you I would do the changes in the version on the jsfest page and link to your original document on the bottom (would do the link thing anyway). Or would you like to integrate it into your document as well?

**Comment by verpixelt** [comment]
update: I have applied a page template and integrated the whole post from @mroderick (I only have to push it)

**Comment by theophani** [comment]
I believe "geeks" is gender neutral, and gendered nouns like that are very passé. If you really believe that saying Geekettes will make women feel more included, I may be sway, but you may find your option changes after you are exposed to research demonstrating how being explicit about gender actually reenforces stereotypes and by choosing to use the gendered variation "Geekette" you reenforce the gendered perception of "Geek".

**Comment by mroderick** [comment]
I'd much prefer to stick with a gender neutral noun. If for some reason "geek" doesn't cut it, then I am more than happy to replace it with another neutral noun.

**Comment by theophani** [comment]
“People! … ”

**Comment by mroderick** [comment]
Works

**Comment by theophani** [comment]
@verpixelt For the record, I appreciate your desire to be inclusive. I just don't think that is the way to do it ;)

**Comment by verpixelt** [comment]
We don't have to change it at all if the majority thinks that 'geeks' fit. Personally I find it more pleasing like "Welcome ladies and gentlemen" but never mind. If we could agree on how to deal with my second question I may be able to publish the page today/tomorrow. (and thanks for your input)

**Comment by mroderick** [comment]
It's a bit difficult to answer the second question without a bit more context. Have you got the changes in a branch somewhere? Or can you link to your friend's content?

**Comment by verpixelt** [comment]
Yeah sure the one thing is just a link to a foursquare list of amazing places https://de.foursquare.com/ffffux/list/cssconfeus-favourites and the oher is this blog post on the CSSConf 2013 page: http://2013.cssconf.eu/2013/08/27/things-to-do-in-berlin.html

**Comment by mroderick** [comment]
I think those are both great resources to link to!
