### ISSUE TITLE
Informal Gathering of JSConfeu + CSSConfeu organisers

### ISSUE THREAD

**Issue by Onna-no-hito** [rmehner/jsfest.berlin#30]
hey ladies and gents,

hoping we can all meet up informally for food and/or drinks sometime to discuss events and ideas surrounding the big week(s)! here is a doodle, please fill it out-- NOW:)
http://doodle.com/hdycmue2qhdsiyz7xq3t2zg9/admin#table

thank-you!
cheers,rachel

**Comment by Onna-no-hito** [comment]
hey peeps, the idea is just to have an informal gathering of everyone who is helping or hoping to organise something around jsfest-- if no one fills out the doodle-- is there another suggestion for how we could have an informal face-to-face discussion as a group? any planning meetings in the works? though i still personally think an informal meetup would be nicer:)  http://doodle.com/hdycmue2qhdsiyz7xq3t2zg9/admin#table

**Comment by janl** [comment]
I’m game! :)

**Comment by schoolofma** [comment]
hi everyone, thanks to those who participated! in the end the date selected is: 
Friday, June 27, 2014 8:00 PM

if anyone else can make it that maybe didn't catch the doodle-wave, please join us!

now, any venue suggestions?
:)

**Comment by rmehner** [comment]
I'd prefer something close to co.up (if not even co.up), as I'm invited to an party right next to it on that day ;)

**Comment by Kriesse** [comment]
Same problem as @rmehner :)
How about one of the bars in Dresdner Straße (e.g. Würgeengel)?

PS: @Onna-no-hito, do you want to be my +1 on that party (it’s Till's office warm-up)? So we can just all roll together :)

**Comment by schoolofma** [comment]
hey @Kriesse - like the idea of a place on Dresdner Straße!
shall i make a reservation? 

ps: yes to +1 !  thanks :)

**Comment by Kriesse** [comment]
@Onna-no-hito  I think there will be BBQ later at the party, so how about we just hit one of the bars - should be fine without reservation.

**Comment by schoolofma** [comment]
@Kriesse yes of course, i don't care about food, just that we meet up:) 

so Würgeengel or TrödlerBar?

**Comment by schoolofma** [comment]
ok i'll make it easy: Friday, June 27, 2014 8:00 PM Würgeengel 
all jsfest organisers invited!

if new people come or anyone has to cancel, msg me so i can keep tabs on rsvp:
rachel@schoolofma.org 

so far we have: Jana, Jan. M. , Robin, Rachel , Kriesse (?)
cheers,see you all then!

**Comment by bitboxer** [comment]
Sorry, can't be there. Will be at a festival :dancers:

**Comment by maxfell** [comment]
I would join!

**Comment by Kriesse** [comment]
Thanks everyone who came out last night, was good catching up on each other’s organizers issues :) 
Let’s definitely repeat this! Closing issue for now.
