### ISSUE TITLE
09.09. UpFront Evening

### ISSUE THREAD

**Issue by janl** [rmehner/jsfest.berlin#5]

**Comment by Kriesse** [comment]
Will definitely happen.
Only the "Special Evening" is tentative.

**Comment by janl** [comment]
@Kriesse feel free to adjust the labels at will :)

**Comment by Kriesse** [comment]
cc @maxfell @espy @QateOh 

@theophani Can we count you in for talk and / or host?

We should ask Alex Sexton if he wants to give his talk from DHTML conf.

**Comment by theophani** [comment]
Yes. Not sure exactly what yet.

**Comment by Kriesse** [comment]
Ping @espy @QateOh @maxfell 
Upfront Organizers Meetup June 24, 8pm, ok?

**Comment by espy** [comment]
Argh, I just realised I'm not free that evening after all, sorry. Thursday the 26th?

**Comment by Kriesse** [comment]
I’m booked on Thursday. Could do Monday 23rd instead, or Wed 25th.

**Comment by espy** [comment]
Monday is good!

**Comment by QateOh** [comment]
Ich kann Montag nicht. Sorrey.

**Comment by QateOh** [comment]
Dienstag -Freitag alles tutti.

**Comment by QateOh** [comment]
Wednesday 25th?

**Comment by Kriesse** [comment]
@espy @QateOh @maxfell Did we decide yet?
I can do tonight, Tuesday or Wednesday, but need to know asap.

**Comment by espy** [comment]
Then it'll have to be Wednesday, 20:00. Where do we meet?

**Comment by Kriesse** [comment]
Ok, unless Max vetoes: 
Wednesday, June 25, 8pm.

Location options:
- Kriesse’s kitchentable
- GriGri (might be to cold/rainy)
- ??

**Comment by QateOh** [comment]
Natanja&heinrich?

Von meinem iPhone gesendet

**Comment by Kriesse** [comment]
Maybe somewhere where we can get dinner?

**Comment by maxfell** [comment]
I'm all right with date/time. We could also go to my place (at Ostkreuz) and grab some Döner/Pizza/Vegan stuff on the way. But I'm open to anything!

**Comment by QateOh** [comment]
Masagnello, 
Manuela tapas, 
Liberda, 
Melbourne canteen, 
Ankerklause, 
Morena,
...

Von meinem iPhone gesendet

**Comment by QateOh** [comment]
Oh, and Max, thanks for the offer:) in eine Kneipe/Restauration zu gehen ist vielleicht angenehm wegen food und Getränken vor Ort. Aber brauchen wir wifi?? Morena und Melbourne canteen haben glaub ich..

Von meinem iPhone gesendet

**Comment by QateOh** [comment]
Hat jemand was gegen Mebourne Canteen morgen abend?? Dann kann ich dort einen Tisch reservieren. http://www.melbournecanteen.com/de/karte/abendessen/

**Comment by Kriesse** [comment]
Works for me!

**Comment by Kriesse** [comment]
@QateOh Did we get a response for the venue at Kotti yet?

@maxfell Any response from Prachtwerk?
