### ISSUE TITLE
Detail pages

### ISSUE THREAD

**Issue by janmonschke** [rmehner/jsfest.berlin#53]
Hi everyone,

I was wondering if somebody is already working on detail pages for the events. For the Web Audio Hack Day we are working on a page that has the time table and some other resources for attendees.
It would be cool to have detail pages in a consistent design :)

/Jan

**Comment by Dangoo** [comment]
Hey Jan,

it's my plan to build some, but currently I'm not shure if we should do
separate pages or slide in layers for details. Somebody else got an opinion?

Cheers Daniel


## 

## 

Daniel Gooß, Development

daniel.gooss@sinnerschrader.com

SinnerSchrader Deutschland GmbH | SinnerSchrader Group
Völckersstraße 38, 22765 Hamburg, Germany

Amtsgericht Hamburg HRB-Nr. 63663
Geschäftsführer: Matthias Schrader (Sprecher), Holger Blank,
Thomas Dyckhoff, Dr. Lars Finke, Martin Gassner, Nils Wollny

Büros: Hamburg, Frankfurt a. M., München, Prag

http://www.sinnerschrader.com | Radical Relationships

**Comment by finnp** [comment]
Keep it decentral, if people want to use other people's design, they can fork it. Many events already have their pages.
