### ISSUE TITLE
10.09. Angular meetup

### ISSUE THREAD

**Issue by janl** [rmehner/jsfest.berlin#6]
@rin, what is @agento’s GitHub?

**Comment by rin** [comment]
@janv—

**Comment by janl** [comment]
Thanks!

**Comment by janv** [comment]
It's on September 10th.
http://www.meetup.com/AngularJS-Meetup-Berlin/events/182645922/

**Comment by janl** [comment]
@janv As Bitcrowd are planning to do their hackathon that day, do you have another venue for this? If not we are happy to help find one :)

**Comment by bitboxer** [comment]
Hm...can't we find a way to integrate both? This would create a "two track" event.

**Comment by janl** [comment]
I don’t know if your office can host two distinct events.

**Comment by bitboxer** [comment]
No, we can't. But at least let's think about what we can do to avoid two tracks on the same day :wink: . There are other days with two events, too. Do we want that? I prefer a one track thing but I am okay with more than one event at the same time if the group decided to do it this way. Sorry if you already talked about that in the skype call.

**Comment by janl** [comment]
We definitely want many many events going on at the same time. Remember that the individual events can only hold a fraction of the people who would go to reject/cssconf/jsconf, so we actually need some variety :)

It should be easy to find another venue for this one.

**Comment by janv** [comment]
I'm not 100% sure of our schedule for the rest of the year.
We have actually been considering making the Angular meetup a bi-monthly event.

**Comment by janl** [comment]
I’t be fantastic to have an angular event for jsfest regardless of your schedule :)

**Comment by janv** [comment]
I'll talk to @AliAlbazaz about it

**Comment by rmehner** [comment]
Current plan is to also have a BerlinJS meetup on that day, see #22. Reject.JS will have around 200 people (maybe a bit more), so there's definitely place for more than one meetup. Or we find a venue where we can have both at the same time, so people can roam between the Angular meetup and the other one.

FYI: Added @AliAlbazaz to this repo

**Comment by janv** [comment]
I've recently talked to different people regarding the future of the Angular Meetup.
One idea that we're thinking about is to design a meeting more in the form of a workshop, where beginner are free to poke questions at more experienced people, show code to each other etc. instead of having presentations.

I was thinking of using the september meetup for that.

**Comment by janl** [comment]
Sounds great to me!

**Comment by janv** [comment]
So, we put up some info on the Meetup page and [prepared a branch](https://github.com/rmehner/jsfest.berlin/tree/angularjs).
I'm trying to figure out a solution to the venue problem with @AliAlbazaz and open a pull request afterwards.
